/*básicas reglas de estilo:
todo en mayusculas
las constraints usan dos letras para referirse a cada tabla, que puedes ver en la línea del create
el nombre de las FKs son la tabla misma, luego la otra, luego FK*/

--no realizar cambios a este fichero sin consultar EXTENSIVAMENTE con el equipo
--faltan constraints de tipo check, sinónimos, etc

--empezamos con la creación de tablas
DROP TABLE PLAYER CASCADE CONSTRAINTS;
DROP TABLE TEAM_OWNER CASCADE CONSTRAINTS;
DROP TABLE DB_ADMIN CASCADE CONSTRAINTS;
DROP TABLE DB_USER CASCADE CONSTRAINTS;
DROP TABLE TEAM CASCADE CONSTRAINTS;
DROP TABLE GAME_RESULT CASCADE CONSTRAINTS;
DROP TABLE GAME CASCADE CONSTRAINTS;
DROP TABLE MATCHSET CASCADE CONSTRAINTS;
DROP TABLE LEAGUE CASCADE CONSTRAINTS;


CREATE TABLE TEAM_OWNER ( --TO
  ID_TO NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  USERNAME VARCHAR(12) NOT NULL,
  PASSWD VARCHAR(12) NOT NULL,
  FULL_NAME VARCHAR(30) NOT NULL,
  TELEPHONE VARCHAR(9) NOT NULL,

  CONSTRAINT TO_FK PRIMARY KEY (ID_TO)
);

CREATE TABLE DB_ADMIN ( --AD
  ID_AD NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  USERNAME VARCHAR(12) NOT NULL,
  PASSWD VARCHAR(12) NOT NULL,
  
  CONSTRAINT AD_FK PRIMARY KEY (ID_AD)
);

CREATE TABLE DB_USER ( --US
  ID_US NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  USERNAME VARCHAR(12) NOT NULL,
  PASSWD VARCHAR(12) NOT NULL,
  
  CONSTRAINT US_FK PRIMARY KEY (ID_US)
);

CREATE TABLE TEAM ( --TM
  ID_TM NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  TEAM_NAME VARCHAR(12) NOT NULL,
  NATIONALITY VARCHAR(2),
  TEAM_OWNER NUMBER(5) NOT NULL,
  
  CONSTRAINT TM_PK PRIMARY KEY (ID_TM),
  CONSTRAINT TM_TO_FK FOREIGN KEY (TEAM_OWNER) REFERENCES TEAM_OWNER (ID_TO)
);

CREATE TABLE PLAYER ( --PL
  ID_PL NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  FULL_NAME VARCHAR(30) NOT NULL,
  NICKNAME VARCHAR(12) NOT NULL,
  SALARY NUMBER(8,2) NOT NULL,
  EMAIL VARCHAR(20) NOT NULL,
  TEAM NUMBER(5),

  CONSTRAINT PL_PK PRIMARY KEY (ID_PL),
  CONSTRAINT PL_TM_FK FOREIGN KEY (TEAM) REFERENCES TEAM (ID_TM)
);

CREATE TABLE LEAGUE ( --LG
  ID_LG NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  LEAGUE_NAME VARCHAR(20) NOT NULL,
  
  CONSTRAINT LG_PK PRIMARY KEY (ID_LG)
);  

CREATE TABLE MATCHSET ( --MS
  ID_MS NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  LEAGUE NUMBER(5),
  
  CONSTRAINT MS_LG_FK FOREIGN KEY (LEAGUE) REFERENCES LEAGUE (ID_LG),
  CONSTRAINT MS_PK PRIMARY KEY (ID_MS)
);

CREATE TABLE GAME ( --GA
  ID_GA NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  MATCHSET NUMBER(5) NOT NULL,
  DATE_TIME DATE,

  CONSTRAINT GA_MS_FK FOREIGN KEY (MATCHSET) REFERENCES MATCHSET (ID_MS),
  CONSTRAINT GA_PK PRIMARY KEY (ID_GA)
);

CREATE TABLE GAME_RESULT ( --GR
  TEAM NUMBER(5),
  GAME NUMBER(5),
  SCORE NUMBER(3),

  CONSTRAINT GR_TM_FK FOREIGN KEY (TEAM) REFERENCES TEAM (ID_TM),
  CONSTRAINT GR_GA_FK FOREIGN KEY (GAME) REFERENCES GAME (ID_GA),
  CONSTRAINT GR_PK PRIMARY KEY (TEAM, GAME)
);


--ahora vamos con la creación de triggers y procesos



CREATE OR REPLACE TRIGGER TM_PL_MAX --a esto le falta una solución para el prolema de tabla mutante
BEFORE INSERT OR UPDATE OF TEAM
ON PLAYER
FOR EACH ROW
DECLARE
  MEMBERS NUMBER;
BEGIN
  SELECT COUNT(*) INTO MEMBERS FROM PLAYER WHERE TEAM=:NEW.TEAM;
  IF MEMBERS >= 6 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Se ha alcanzado el límite de miembros en un equipo.');
  END IF;
END;

