/*básicas reglas de estilo:
todo en mayusculas
las constraints usan dos letras para referirse a cada tabla, que puedes ver en la línea del create
el nombre de las FKs son la tabla misma, luego la otra, luego FK*/

--no realizar cambios a este fichero sin consultar EXTENSIVAMENTE con el equipo
--faltan constraints de tipo check, sinónimos, etc

--empezamos con la creación de tablas
DROP TABLE PLAYER CASCADE CONSTRAINTS;
DROP TABLE TEAM_OWNER CASCADE CONSTRAINTS;
DROP TABLE DB_ADMIN CASCADE CONSTRAINTS;
DROP TABLE DB_USER CASCADE CONSTRAINTS;
DROP TABLE TEAM CASCADE CONSTRAINTS;
DROP TABLE GAME_RESULT CASCADE CONSTRAINTS;
DROP TABLE GAME CASCADE CONSTRAINTS;
DROP TABLE MATCHSET CASCADE CONSTRAINTS;
DROP TABLE LEAGUE CASCADE CONSTRAINTS;


CREATE TABLE TEAM_OWNER ( --TO
  ID_TO NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  USERNAME VARCHAR(12),
  PASSWD VARCHAR(12) NOT NULL,
  FULL_NAME VARCHAR(30) NOT NULL,
  TELEPHONE VARCHAR(9) NOT NULL,

  CONSTRAINT TO_FK PRIMARY KEY (ID_TO),
  CONSTRAINT TO_UK UNIQUE (USERNAME)
);

CREATE TABLE DB_ADMIN ( --AD
  ID_AD NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  USERNAME VARCHAR(12),
  PASSWD VARCHAR(12) NOT NULL,
  
  CONSTRAINT AD_FK PRIMARY KEY (ID_AD),
  CONSTRAINT AD_UK UNIQUE (USERNAME)
);

CREATE TABLE DB_USER ( --US
  ID_US NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  USERNAME VARCHAR(12),
  PASSWD VARCHAR(12) NOT NULL,
  
  CONSTRAINT US_FK PRIMARY KEY (ID_US),
  CONSTRAINT US_UK UNIQUE (USERNAME)
);

CREATE TABLE TEAM ( --TM
  ID_TM NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  TEAM_NAME VARCHAR(12) NOT NULL,
  NATIONALITY VARCHAR(2),
  TEAM_OWNER NUMBER(5) NOT NULL,
  
  CONSTRAINT TM_PK PRIMARY KEY (ID_TM),
  CONSTRAINT TM_TO_FK FOREIGN KEY (TEAM_OWNER) REFERENCES TEAM_OWNER (ID_TO)
);

CREATE TABLE PLAYER ( --PL
  ID_PL NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  FULL_NAME VARCHAR(30) NOT NULL,
  NICKNAME VARCHAR(12) NOT NULL,
  SALARY NUMBER(8,2) NOT NULL,
  EMAIL VARCHAR(20) NOT NULL,
  TEAM NUMBER(5),

  CONSTRAINT PL_PK PRIMARY KEY (ID_PL),
  CONSTRAINT PL_TM_FK FOREIGN KEY (TEAM) REFERENCES TEAM (ID_TM),
  CONSTRAINT PL_SAL_MIN CHECK (SALARY>=10302.60)
);

CREATE TABLE LEAGUE ( --LG
  ID_LG NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  LEAGUE_NAME VARCHAR(20) NOT NULL,
  
  CONSTRAINT LG_PK PRIMARY KEY (ID_LG)
);  

CREATE TABLE MATCHSET ( --MS
  ID_MS NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  LEAGUE NUMBER(5),
  
  CONSTRAINT MS_LG_FK FOREIGN KEY (LEAGUE) REFERENCES LEAGUE (ID_LG),
  CONSTRAINT MS_PK PRIMARY KEY (ID_MS)
);

CREATE TABLE GAME ( --GA
  ID_GA NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  MATCHSET NUMBER(5) NOT NULL,
  DATE_TIME DATE,

  CONSTRAINT GA_MS_FK FOREIGN KEY (MATCHSET) REFERENCES MATCHSET (ID_MS),
  CONSTRAINT GA_PK PRIMARY KEY (ID_GA)
);

CREATE TABLE GAME_RESULT ( --GR
  TEAM NUMBER(5),
  GAME NUMBER(5),
  SCORE NUMBER(3),

  CONSTRAINT GR_TM_FK FOREIGN KEY (TEAM) REFERENCES TEAM (ID_TM),
  CONSTRAINT GR_GA_FK FOREIGN KEY (GAME) REFERENCES GAME (ID_GA),
  CONSTRAINT GR_PK PRIMARY KEY (TEAM, GAME)
);
/

--ahora vamos con la creaci?n de triggers y procesos
CREATE OR REPLACE PACKAGE TRIGGER_MT AS --este trigger existe solo para la creacion de la variable que contiene
  TEMP_PLAYERS PLAYER%ROWTYPE := NULL; --la cual existe solo para prevenir el error de tabla mutante
END;
/
CREATE OR REPLACE TRIGGER PL_MT_FIX --este trigger existe solo para resolver el problema de tabla mutante en los siguientes dos triggers
BEFORE INSERT OR UPDATE OF TEAM --se ejecuta antes que los dos siguientes triggers
ON PLAYER
FOR EACH ROW
BEGIN
  TRIGGER_MT.TEMP_PLAYERS.SALARY := :NEW.SALARY; --y todo lo que hace es introducir los nuevos valores a la variable que declaramos antes
  TRIGGER_MT.TEMP_PLAYERS.TEAM := :NEW.TEAM;
END;
/
CREATE OR REPLACE TRIGGER TM_PL_MAX --este trigger limita la cantidad de miembros por equipo
BEFORE INSERT OR UPDATE OF TEAM
ON PLAYER
DECLARE
  MEMBERS NUMBER;
BEGIN
  SELECT COUNT(*) INTO MEMBERS FROM PLAYER WHERE TEAM=TRIGGER_MT.TEMP_PLAYERS.TEAM; --una select para calcular la cantidad de miembros actuales en el equipo
  IF MEMBERS >= 6 THEN --si eso es mayor que 6 entonces 
    RAISE_APPLICATION_ERROR(-20001, 'Se ha alcanzado el limite de miembros en un equipo.'); --salta la excepcion
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TM_SL_MAX --este trigger limita el salario total de los miembros del equipo
BEFORE INSERT OR UPDATE OF TEAM
ON PLAYER
DECLARE
  TEAM_SALARY NUMBER;
BEGIN
  SELECT SUM(SALARY) INTO TEAM_SALARY FROM PLAYER WHERE TEAM = TRIGGER_MT.TEMP_PLAYERS.SALARY; --aqui calculamos la suma del salario de los ya existentes miembros del equipo
  TEAM_SALARY := TEAM_SALARY + TRIGGER_MT.TEMP_PLAYERS.SALARY; --y aqui le sumamos a eso el salario del nuevo miembro
  IF TEAM_SALARY >= 200000 THEN --si la suma de los totales es mayor a 200000 entonces
    RAISE_APPLICATION_ERROR(-20002, 'El salario total del equipo no debe ser mayor a 200000.'); --salta la excepcion
  END IF;
END;
/