/*esto son los inserts

-----------------NO CAMBIAR SIN CONSULTAR CON EL EQUIPO------------------------------



mismas reglas de estilo que el DDL
*/
/*----DB_ADMIN----*/
INSERT INTO DB_ADMIN(USERNAME,PASSWD) VALUES('root','abcde!2345');


/*----DB_USER----
  estos serían los "default" */
INSERT INTO DB_USER(USERNAME,PASSWD) VALUES('usuario1','dbuser');
INSERT INTO DB_USER(USERNAME,PASSWD) VALUES('usuario2','dbuser');
INSERT INTO DB_USER(USERNAME,PASSWD) VALUES('Noe','noesito');
INSERT INTO DB_USER(USERNAME,PASSWD) VALUES('Filomena','sancha56');

/*----TEAM_OWNER----*/
INSERT INTO TEAM_OWNER(USERNAME,PASSWD,FULL_NAME,TELEPHONE) VALUES('Eunei','Neili1989','Euan Neilina','654778798');
INSERT INTO TEAM_OWNER(USERNAME,PASSWD,FULL_NAME,TELEPHONE) VALUES('Pateuk','Euke1986','Patxi Eukene','688546355');
INSERT INTO TEAM_OWNER(USERNAME,PASSWD,FULL_NAME,TELEPHONE) VALUES('Svyyar','Yar1990','Svyatopolk Yaroslava','878546377');
INSERT INTO TEAM_OWNER(USERNAME,PASSWD,FULL_NAME,TELEPHONE) VALUES('Isaume','Ume1992','Isamu Ume','57789652');
INSERT INTO TEAM_OWNER(USERNAME,PASSWD,FULL_NAME,TELEPHONE) VALUES('Timos','Osm1986','Timoteo Osmo','588744122');
INSERT INTO TEAM_OWNER(USERNAME,PASSWD,FULL_NAME,TELEPHONE) VALUES('Ruwal','Wal1979','Rudi Walburga','698599324');