CREATE OR REPLACE PACKAGE LOGIN AS
  PROCEDURE GET_TYPE (UN VARCHAR2, PW VARCHAR2, AC OUT NUMBER); --UN es el nombre de usuario, PW la contraseña, y AC el tipo de cuenta
END;
  
CREATE OR REPLACE PACKAGE BODY LOGIN AS
  PROCEDURE GET_TYPE (UN VARCHAR2, PW VARCHAR2, AC OUT NUMBER) IS
  CNT NUMBER;
    BEGIN
      SELECT COUNT(*) INTO CNT FROM DB_USER WHERE USERNAME = UN AND PASSWD = PW; --si el usuario y contraseña introducidos se encuentran en una de las filas de la table DB_USER, AC es 1
      IF CNT = 1 THEN
        AC := 1;
      ELSE
        SELECT COUNT(*) INTO CNT FROM TEAM_OWNER WHERE USERNAME = UN AND PASSWD = PW;--si se encuentran en la tabla TEAM_OWNER, AC es 2
        IF CNT = 1 THEN
          AC := 2;
        ELSE
          SELECT COUNT(*) INTO CNT FROM DB_ADMIN WHERE USERNAME = UN AND PASSWD = PW;--si se encuentran en DB_ADMIN, AC es 3
          IF CNT = 1 THEN
            AC := 3;
          ELSE 
            AC := 0; --y si no se encuentra en ninguna, AC es 0
          END IF;
        END IF;
      END IF;
    END GET_TYPE;  
END;

----

CREATE OR REPLACE PACKAGE CLASSIFICATION AS
  TYPE TEAMS_OUT IS TABLE OF VARCHAR2(12);
  TYPE SCORE_OUT IS TABLE OF NUMBER(3);
  
  PROCEDURE GET_CLASSIFICATION (ID_LG NUMBER, TEAMS OUT TEAMS_OUT, SCORE OUT SCORE_OUT);
  FUNCTION GET_SCORE(ID_TM NUMBER) RETURN NUMBER;
  FUNCTION GET_NAME(ID_TM NUMBER) RETURN VARCHAR2;
END;
  
CREATE OR REPLACE PACKAGE BODY CLASSIFICATION AS
  
  PROCEDURE GET_CLASSIFICATION (ID_LG NUMBER, TEAMS OUT TEAMS_OUT, SCORE OUT SCORE_OUT) IS
      CURSOR TEAM_IDS IS SELECT ID_TM FROM TEAM WHERE ID_TM IN 
        (SELECT GAME FROM GAME_RESULT WHERE GAME IN
        (SELECT ID_GA FROM GAME WHERE MATCHSET IN
        (SELECT ID_MS FROM MATCHSET WHERE LEAGUE=ID_LG)));
    BEGIN
      TEAMS := TEAMS_OUT();
      SCORE := SCORE_OUT();
    END;
  
  FUNCTION GET_NAME(ID_TM NUMBER) RETURN VARCHAR2 IS
        T_NAME VARCHAR2(12);
    BEGIN
      SELECT TEAM_NAME INTO T_NAME FROM TEAM WHERE TEAM.ID_TM=ID_TM;
      RETURN T_NAME;
    END;
  
  FUNCTION GET_SCORE(ID_TM NUMBER) RETURN NUMBER IS
    BEGIN      
      RETURN NULL;
    END;
  
END;


SELECT CLASSIFICATION.LIST_TEAMS FROM DUAL;


























