CREATE OR REPLACE PACKAGE LOGIN AS
  PROCEDURE GET_TYPE (UN VARCHAR2, PW VARCHAR2, AC OUT NUMBER);
END;
  
CREATE OR REPLACE PACKAGE BODY LOGIN AS
  PROCEDURE GET_TYPE (UN VARCHAR2, PW VARCHAR2, AC OUT NUMBER) IS
  CNT NUMBER;
    BEGIN
      SELECT COUNT(*) INTO CNT FROM DB_USER WHERE USERNAME = UN AND PASSWD = PW;
      IF CNT = 1 THEN
        AC := 1;
      ELSE
        SELECT COUNT(*) INTO CNT FROM TEAM_OWNER WHERE USERNAME = UN AND PASSWD = PW;
        IF CNT = 1 THEN
          AC := 2;
        ELSE
          SELECT COUNT(*) INTO CNT FROM DB_ADMIN WHERE USERNAME = UN AND PASSWD = PW;
          IF CNT = 1 THEN
            AC := 3;
          ELSE 
          AC := 0;
          END IF;
        END IF;
      END IF;
    END GET_TYPE;  
END;

select login.get_type('root', 'abcde!2345') from dual;