CREATE OR REPLACE PACKAGE LOGIN AS
  FUNCTION GET_TYPE (UN VARCHAR2, PW VARCHAR2) RETURN NUMBER;
END;
  
CREATE OR REPLACE PACKAGE BODY LOGIN AS
  FUNCTION GET_TYPE (UN VARCHAR2, PW VARCHAR2) RETURN NUMBER IS
  CNT NUMBER;
    BEGIN
      SELECT COUNT(*) INTO CNT FROM DB_USER WHERE USERNAME = UN AND PASSWD = PW;
      IF CNT = 1 THEN
        RETURN 1;
      ELSE
        SELECT COUNT(*) INTO CNT FROM TEAM_OWNER WHERE USERNAME = UN AND PASSWD = PW;
        IF CNT = 1 THEN
          RETURN 2;
        ELSE
          SELECT COUNT(*) INTO CNT FROM DB_ADMIN WHERE USERNAME = UN AND PASSWD = PW;
          IF CNT = 1 THEN
            RETURN 3;
          ELSE RETURN 0;
          END IF;
        END IF;
      END IF;
    END GET_TYPE;  
END;